#############################################################################
# Generated by qmake (3.1) (Qt 5.12.4)
# Makefile for building: ffnode
# Project:  FFmpegGUI.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile FFmpegGUI.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -Os -fomit-frame-pointer -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -fpermissive -std=c++0x -Os -fomit-frame-pointer -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I./ffmpeg -I. -isystem /usr/include/QtWidgets -isystem /usr/include/QtGui -isystem /usr/include/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ffnode1.0.0
DISTDIR = /mnt/c/Users/Leon/Desktop/projects/FFmpegGUI/.tmp/ffnode1.0.0
LINK          = g++
LFLAGS        = -Wl,--as-needed -Wl,-O1
LIBS          = $(SUBLIBS) -L -./ffmpeg/libavdevice -lavdevice -L -./ffmpeg/libavformat -lavformat -L -./ffmpeg/libavfilter -lavfilter -L -./ffmpeg/libavcodec -lavcodec -L -./ffmpeg/libswscale -lswscale -L -./ffmpeg/libavutil -lavutil -L -./ffmpeg/libswresample -lswresample -lbz2 -lm -lz -ldl /usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Core.so /usr/lib/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/connectivity.cpp \
		src/externs.cpp \
		src/filter.cpp \
		src/filterButton.cpp \
		src/filtersList.cpp \
		src/filtersWidget.cpp \
		src/inspectionWidget.cpp.cc \
		src/main.cpp \
		src/mainwindow.cpp \
		src/pad.cpp \
		src/pipeline.cpp \
		src/pipelineParser.cpp \
		src/pipelineSaver.cpp \
		src/player.cpp \
		src/scene.cpp \
		src/view.cpp \
		src/wire.cpp qrc_images.cpp \
		moc_filtersList.cpp \
		moc_filtersWidget.cpp \
		moc_inspectionWidget.cpp \
		moc_mainwindow.cpp \
		moc_pipeline.cpp \
		moc_player.cpp \
		moc_view.cpp \
		moc_wire.cpp
OBJECTS       = connectivity.o \
		externs.o \
		filter.o \
		filterButton.o \
		filtersList.o \
		filtersWidget.o \
		inspectionWidget.cpp.o \
		main.o \
		mainwindow.o \
		pad.o \
		pipeline.o \
		pipelineParser.o \
		pipelineSaver.o \
		player.o \
		scene.o \
		view.o \
		wire.o \
		qrc_images.o \
		moc_filtersList.o \
		moc_filtersWidget.o \
		moc_inspectionWidget.o \
		moc_mainwindow.o \
		moc_pipeline.o \
		moc_player.o \
		moc_view.o \
		moc_wire.o
DIST          = /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/linux.conf \
		/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt5/mkspecs/features/uic.prf \
		/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		FFmpegGUI.pro ui_filtersList.h \
		ui_filtersWidget.h \
		ui_inspectionWidget.h \
		src/connectivity.h \
		src/externs.h \
		src/filter.h \
		src/filterButton.h \
		src/filtersList.h \
		src/filtersWidget.h \
		src/inspectionWidget.h \
		src/mainwindow.h \
		src/pad.h \
		src/pipeline.h \
		src/pipelineParser.h \
		src/pipelineSaver.h \
		src/player.h \
		src/scene.h \
		src/view.h \
		src/wire.h src/connectivity.cpp \
		src/externs.cpp \
		src/filter.cpp \
		src/filterButton.cpp \
		src/filtersList.cpp \
		src/filtersWidget.cpp \
		src/inspectionWidget.cpp.cc \
		src/main.cpp \
		src/mainwindow.cpp \
		src/pad.cpp \
		src/pipeline.cpp \
		src/pipelineParser.cpp \
		src/pipelineSaver.cpp \
		src/player.cpp \
		src/scene.cpp \
		src/view.cpp \
		src/wire.cpp
QMAKE_TARGET  = ffnode
DESTDIR       = 
TARGET        = ffnode


first: all
####### Build rules

ffnode: ui_filtersList.h ui_filtersWidget.h ui_inspectionWidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FFmpegGUI.pro /usr/lib/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/linux.conf \
		/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt5/mkspecs/features/uic.prf \
		/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		FFmpegGUI.pro \
		images.qrc
	$(QMAKE) -o Makefile FFmpegGUI.pro
/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/qt5/mkspecs/common/unix.conf:
/usr/lib/qt5/mkspecs/common/linux.conf:
/usr/lib/qt5/mkspecs/common/sanitize.conf:
/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt5/mkspecs/common/g++-base.conf:
/usr/lib/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/qt5/mkspecs/qconfig.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/qt5/mkspecs/features/qt_config.prf:
/usr/lib/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt5/mkspecs/features/toolchain.prf:
/usr/lib/qt5/mkspecs/features/default_pre.prf:
/usr/lib/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/qt5/mkspecs/features/default_post.prf:
/usr/lib/qt5/mkspecs/features/warn_on.prf:
/usr/lib/qt5/mkspecs/features/qt.prf:
/usr/lib/qt5/mkspecs/features/resources.prf:
/usr/lib/qt5/mkspecs/features/moc.prf:
/usr/lib/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/qt5/mkspecs/features/uic.prf:
/usr/lib/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/qt5/mkspecs/features/file_copies.prf:
/usr/lib/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/qt5/mkspecs/features/exceptions.prf:
/usr/lib/qt5/mkspecs/features/yacc.prf:
/usr/lib/qt5/mkspecs/features/lex.prf:
FFmpegGUI.pro:
images.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile FFmpegGUI.pro

qmake_all: FORCE


all: Makefile ffnode

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui_filtersList.h ui_filtersWidget.h ui_inspectionWidget.h src/connectivity.h src/externs.h src/filter.h src/filterButton.h src/filtersList.h src/filtersWidget.h src/inspectionWidget.h src/mainwindow.h src/pad.h src/pipeline.h src/pipelineParser.h src/pipelineSaver.h src/player.h src/scene.h src/view.h src/wire.h $(DISTDIR)/
	$(COPY_FILE) --parents src/connectivity.cpp src/externs.cpp src/filter.cpp src/filterButton.cpp src/filtersList.cpp src/filtersWidget.cpp src/inspectionWidget.cpp.cc src/main.cpp src/mainwindow.cpp src/pad.cpp src/pipeline.cpp src/pipelineParser.cpp src/pipelineSaver.cpp src/player.cpp src/scene.cpp src/view.cpp src/wire.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/filtersList.ui src/filtersWidget.ui src/inspectionWidget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		/usr/lib/qt5/bin/rcc \
		icons/savetext.png \
		icons/clear.png \
		icons/unicorn.png \
		icons/help.png \
		icons/buble.png \
		icons/play.png \
		icons/cursor.png \
		icons/automatic.png \
		icons/filt1.png \
		icons/pad1.png \
		icons/exit.png \
		icons/hand.png \
		icons/file.png \
		icons/text.png \
		icons/cursorT.png \
		icons/checked.png \
		icons/xml.png \
		icons/wire.png \
		icons/save.png \
		icons/handT.png \
		icons/padC.png \
		icons/filt1S.png \
		icons/remove.png
	/usr/lib/qt5/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -fpermissive -std=c++0x -Os -fomit-frame-pointer -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_filtersList.cpp moc_filtersWidget.cpp moc_inspectionWidget.cpp moc_mainwindow.cpp moc_pipeline.cpp moc_player.cpp moc_view.cpp moc_wire.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_filtersList.cpp moc_filtersWidget.cpp moc_inspectionWidget.cpp moc_mainwindow.cpp moc_pipeline.cpp moc_player.cpp moc_view.cpp moc_wire.cpp
moc_filtersList.cpp: src/filtersList.h \
		ui_filtersList.h \
		src/filter.h \
		src/pad.h \
		src/player.h \
		src/pipeline.h \
		src/inspectionWidget.h \
		ui_inspectionWidget.h \
		src/filtersWidget.h \
		ui_filtersWidget.h \
		src/externs.h \
		src/filterButton.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Leon/Desktop/projects/FFmpegGUI/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Leon/Desktop/projects/FFmpegGUI -I/mnt/c/Users/Leon/Desktop/projects/FFmpegGUI -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtCore -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-alpine-linux-musl -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/include/fortify -I/usr/include -I/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/include src/filtersList.h -o moc_filtersList.cpp

moc_filtersWidget.cpp: src/filtersWidget.h \
		ui_filtersWidget.h \
		src/filter.h \
		src/pad.h \
		src/player.h \
		src/pipeline.h \
		src/inspectionWidget.h \
		ui_inspectionWidget.h \
		src/filtersWidget.h \
		src/externs.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Leon/Desktop/projects/FFmpegGUI/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Leon/Desktop/projects/FFmpegGUI -I/mnt/c/Users/Leon/Desktop/projects/FFmpegGUI -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtCore -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-alpine-linux-musl -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/include/fortify -I/usr/include -I/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/include src/filtersWidget.h -o moc_filtersWidget.cpp

moc_inspectionWidget.cpp: src/inspectionWidget.h \
		ui_inspectionWidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Leon/Desktop/projects/FFmpegGUI/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Leon/Desktop/projects/FFmpegGUI -I/mnt/c/Users/Leon/Desktop/projects/FFmpegGUI -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtCore -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-alpine-linux-musl -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/include/fortify -I/usr/include -I/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/include src/inspectionWidget.h -o moc_inspectionWidget.cpp

moc_mainwindow.cpp: src/mainwindow.h \
		src/scene.h \
		src/filter.h \
		src/pad.h \
		src/player.h \
		src/pipeline.h \
		src/inspectionWidget.h \
		ui_inspectionWidget.h \
		src/filtersWidget.h \
		ui_filtersWidget.h \
		src/externs.h \
		src/connectivity.h \
		src/view.h \
		src/wire.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Leon/Desktop/projects/FFmpegGUI/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Leon/Desktop/projects/FFmpegGUI -I/mnt/c/Users/Leon/Desktop/projects/FFmpegGUI -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtCore -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-alpine-linux-musl -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/include/fortify -I/usr/include -I/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/include src/mainwindow.h -o moc_mainwindow.cpp

moc_pipeline.cpp: src/pipeline.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Leon/Desktop/projects/FFmpegGUI/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Leon/Desktop/projects/FFmpegGUI -I/mnt/c/Users/Leon/Desktop/projects/FFmpegGUI -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtCore -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-alpine-linux-musl -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/include/fortify -I/usr/include -I/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/include src/pipeline.h -o moc_pipeline.cpp

moc_player.cpp: src/player.h \
		src/pipeline.h \
		src/inspectionWidget.h \
		ui_inspectionWidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Leon/Desktop/projects/FFmpegGUI/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Leon/Desktop/projects/FFmpegGUI -I/mnt/c/Users/Leon/Desktop/projects/FFmpegGUI -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtCore -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-alpine-linux-musl -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/include/fortify -I/usr/include -I/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/include src/player.h -o moc_player.cpp

moc_view.cpp: src/view.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Leon/Desktop/projects/FFmpegGUI/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Leon/Desktop/projects/FFmpegGUI -I/mnt/c/Users/Leon/Desktop/projects/FFmpegGUI -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtCore -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-alpine-linux-musl -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/include/fortify -I/usr/include -I/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/include src/view.h -o moc_view.cpp

moc_wire.cpp: src/wire.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Leon/Desktop/projects/FFmpegGUI/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Leon/Desktop/projects/FFmpegGUI -I/mnt/c/Users/Leon/Desktop/projects/FFmpegGUI -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtCore -I/usr/include/c++/8.3.0 -I/usr/include/c++/8.3.0/x86_64-alpine-linux-musl -I/usr/include/c++/8.3.0/backward -I/usr/local/include -I/usr/include/fortify -I/usr/include -I/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/include src/wire.h -o moc_wire.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_filtersList.h ui_filtersWidget.h ui_inspectionWidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_filtersList.h ui_filtersWidget.h ui_inspectionWidget.h
ui_filtersList.h: src/filtersList.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/filtersList.ui -o ui_filtersList.h

ui_filtersWidget.h: src/filtersWidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/filtersWidget.ui -o ui_filtersWidget.h

ui_inspectionWidget.h: src/inspectionWidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/inspectionWidget.ui -o ui_inspectionWidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

connectivity.o: src/connectivity.cpp src/connectivity.h \
		src/externs.h \
		src/wire.h \
		src/pad.h \
		src/filter.h \
		src/player.h \
		src/pipeline.h \
		src/inspectionWidget.h \
		ui_inspectionWidget.h \
		src/filtersWidget.h \
		ui_filtersWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectivity.o src/connectivity.cpp

externs.o: src/externs.cpp src/externs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o externs.o src/externs.cpp

filter.o: src/filter.cpp src/filter.h \
		src/pad.h \
		src/player.h \
		src/pipeline.h \
		src/inspectionWidget.h \
		ui_inspectionWidget.h \
		src/filtersWidget.h \
		ui_filtersWidget.h \
		src/externs.h \
		src/scene.h \
		src/connectivity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filter.o src/filter.cpp

filterButton.o: src/filterButton.cpp src/filterButton.h \
		src/scene.h \
		src/filter.h \
		src/pad.h \
		src/player.h \
		src/pipeline.h \
		src/inspectionWidget.h \
		ui_inspectionWidget.h \
		src/filtersWidget.h \
		ui_filtersWidget.h \
		src/externs.h \
		src/connectivity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filterButton.o src/filterButton.cpp

filtersList.o: src/filtersList.cpp src/filtersList.h \
		ui_filtersList.h \
		src/filter.h \
		src/pad.h \
		src/player.h \
		src/pipeline.h \
		src/inspectionWidget.h \
		ui_inspectionWidget.h \
		src/filtersWidget.h \
		ui_filtersWidget.h \
		src/externs.h \
		src/filterButton.h \
		src/scene.h \
		src/connectivity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filtersList.o src/filtersList.cpp

filtersWidget.o: src/filtersWidget.cpp src/filtersWidget.h \
		ui_filtersWidget.h \
		src/filter.h \
		src/pad.h \
		src/player.h \
		src/pipeline.h \
		src/inspectionWidget.h \
		ui_inspectionWidget.h \
		src/externs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filtersWidget.o src/filtersWidget.cpp

inspectionWidget.cpp.o: src/inspectionWidget.cpp.cc src/inspectionWidget.h \
		ui_inspectionWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inspectionWidget.cpp.o src/inspectionWidget.cpp.cc

main.o: src/main.cpp src/player.h \
		src/pipeline.h \
		src/inspectionWidget.h \
		ui_inspectionWidget.h \
		src/mainwindow.h \
		src/scene.h \
		src/filter.h \
		src/pad.h \
		src/filtersWidget.h \
		ui_filtersWidget.h \
		src/externs.h \
		src/connectivity.h \
		src/view.h \
		src/wire.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/scene.h \
		src/filter.h \
		src/pad.h \
		src/player.h \
		src/pipeline.h \
		src/inspectionWidget.h \
		ui_inspectionWidget.h \
		src/filtersWidget.h \
		ui_filtersWidget.h \
		src/externs.h \
		src/connectivity.h \
		src/view.h \
		src/wire.h \
		src/filtersList.h \
		ui_filtersList.h \
		src/filterButton.h \
		src/pipelineParser.h \
		src/pipelineSaver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

pad.o: src/pad.cpp src/pad.h \
		src/filter.h \
		src/player.h \
		src/pipeline.h \
		src/inspectionWidget.h \
		ui_inspectionWidget.h \
		src/filtersWidget.h \
		ui_filtersWidget.h \
		src/externs.h \
		src/connectivity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pad.o src/pad.cpp

pipeline.o: src/pipeline.cpp src/pipeline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pipeline.o src/pipeline.cpp

pipelineParser.o: src/pipelineParser.cpp src/pipelineParser.h \
		src/pipeline.h \
		src/scene.h \
		src/filter.h \
		src/pad.h \
		src/player.h \
		src/inspectionWidget.h \
		ui_inspectionWidget.h \
		src/filtersWidget.h \
		ui_filtersWidget.h \
		src/externs.h \
		src/connectivity.h \
		src/wire.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pipelineParser.o src/pipelineParser.cpp

pipelineSaver.o: src/pipelineSaver.cpp src/pipelineSaver.h \
		src/pipeline.h \
		src/scene.h \
		src/filter.h \
		src/pad.h \
		src/player.h \
		src/inspectionWidget.h \
		ui_inspectionWidget.h \
		src/filtersWidget.h \
		ui_filtersWidget.h \
		src/externs.h \
		src/connectivity.h \
		src/pipelineParser.h \
		src/wire.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pipelineSaver.o src/pipelineSaver.cpp

player.o: src/player.cpp src/player.h \
		src/pipeline.h \
		src/inspectionWidget.h \
		ui_inspectionWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o src/player.cpp

scene.o: src/scene.cpp src/scene.h \
		src/filter.h \
		src/pad.h \
		src/player.h \
		src/pipeline.h \
		src/inspectionWidget.h \
		ui_inspectionWidget.h \
		src/filtersWidget.h \
		ui_filtersWidget.h \
		src/externs.h \
		src/connectivity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scene.o src/scene.cpp

view.o: src/view.cpp src/view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o src/view.cpp

wire.o: src/wire.cpp src/wire.h \
		src/pad.h \
		src/filter.h \
		src/player.h \
		src/pipeline.h \
		src/inspectionWidget.h \
		ui_inspectionWidget.h \
		src/filtersWidget.h \
		ui_filtersWidget.h \
		src/externs.h \
		src/connectivity.h \
		src/scene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wire.o src/wire.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_filtersList.o: moc_filtersList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filtersList.o moc_filtersList.cpp

moc_filtersWidget.o: moc_filtersWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filtersWidget.o moc_filtersWidget.cpp

moc_inspectionWidget.o: moc_inspectionWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inspectionWidget.o moc_inspectionWidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_pipeline.o: moc_pipeline.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pipeline.o moc_pipeline.cpp

moc_player.o: moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_player.o moc_player.cpp

moc_view.o: moc_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view.o moc_view.cpp

moc_wire.o: moc_wire.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wire.o moc_wire.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

